# Contains configuration for our gcloud app engine application

# runtime is whta executable to use to run our code
runtime: nodejs20

# we'll also set the maximum number of instances to launch to 1
automatic_scaling:
  max_instances: 1

# You can specify a service name - it uses default otherwise
# service: myservice

env_variables:
    AMCLOUD: "gcloud"
    CLIENTID: "1024553040956-opjct211r8tsbl6rga5n79chv03todkm.apps.googleusercontent.com"
    APPURL: "https://coet295-chatroom-387220.uc.r.appspot.com/"
    TENORAPIKEY: "AIzaSyDl0jUTl1a4cmzX9n-bQcFzdLXTrMOOBzM"
# you can also specify handlers